INSERT INTO CFG ("MOD", PAR, VAL) VALUES ('ORDERS', 'PASSWORD', '***');
INSERT INTO CFG ("MOD", PAR, VAL) VALUES ('REPORTS', 'PASSWORD', '***');
INSERT INTO CFG ("MOD", PAR, VAL) VALUES ('TAXI', 'NAME', 'Samara');

COMMIT WORK;
